var localBibliography = {
  ISO24707: {
    id: "ISO24707",
    title: "Information technology — Common Logic (CL) — A framework for a family of logic-based languages",
    date: "2018-07",
    href: "https://www.iso.org/standard/66249.html",
    status: "Published",
    publisher: "ISO/EIC"
  },
  HORST04: {
    id: "HORST04",
    title: "Extending the RDFS Entailment Lemma",
    authors: ["Herman J. ter Horst"],
    date: "2004",
    isbn: "978-3-540-30475-3",
    href: "https://doi.org/10.1007/978-3-540-30475-3_7",
    status: "Conference Proceeding",
    publisher: "Springer, Berlin, Heidelberg"
  },
  HORST05: {
    id: "HORST05",
    title: "Completeness, Decidability and Complexity of Entailment for RDF Schema and a Semantic Extension Involving the OWL Vocabulary",
    authors: ["Herman J. ter Horst"],
    date: "2005",
    href: "https://dx.doi.org/10.2139/ssrn.3199251",
    status: "Conference Proceeding",
    publisher: "Journal of Web Semantics"
  },
  STRIPEDRDF: {
    id: "STRIPEDRDF",
    title: "RDF: Understanding the Striped RDF/XML Syntax",
    editors: ["D. Brickley"],
    date: "2001",
    href: "http://www.w3.org/2001/10/stripes/",
    status: "Team Submission",
    publisher: "W3C"
  },
  "RDF12-CONCEPTS": {aliasOf: "RDF11-CONCEPTS"},
  "RDF12-SEMANTICS": {aliasOf: "RDF11-MT"},
  "RDF12-N-QUADS": {aliasOf: "N-QUADS"},
  "RDF12-N-TRIPLES": {aliasOf: "N-TRIPLES"},
  "RDF12-NEW": {aliasOf: "RDF11-NEW"},
  "RDF12-PRIMER": {aliasOf: "RDF11-PRIMER"},
  "RDF12-SCHEMA": {aliasOf: "RDF11-SCHEMA"},
  "RDF12-TRIG": {aliasOf: "TRIG"},
  "RDF12-TURTLE": {aliasOf: "TURTLE"},
  "RDF12-XML": {aliasOf: "RDF11-XML"},
  "SPARQL12-OVERVIEW": {aliasOf: "SPARQL11-OVERVIEW"},
  "SPARQL12-QUERY": {aliasOf: "SPARQL11-QUERY"},
  "SPARQL12-UPDATE": {aliasOf: "SPARQL11-UPDATE"},
  "SPARQL12-SERVICE-DESCRIPTION": {aliasOf: "SPARQL11-SERVICE-DESCRIPTION"},
  "SPARQL12-FEDERATED-QUERY": {aliasOf: "SPARQL11-FEDERATED-QUERY"},
  "SPARQL12-RESULTS-JSON": {aliasOf: "SPARQL11-RESULTS-JSON"},
  "SPARQL12-RESULTS-CSV-TSV": {aliasOf: "SPARQL11-RESULTS-CSV-TSV"},
  "SPARQL12-XMLRES": {aliasOf: "RDF-SPARQL-XMLRES"},
  "SPARQL12-ENTAILMENT": {aliasOf: "SPARQL11-ENTAILMENT"},
  "SPARQL12-PROTOCOL": {aliasOf: "SPARQL11-PROTOCOL"},
  "SPARQL12-HTTP-RDF-UPDATE": {aliasOf: "SPARQL11-HTTP-RDF-UPDATE"},
};
